version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "8005:80"
        depends_on:
            - db
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=exchange_rates
            - DB_USERNAME=root
            - DB_PASSWORD=root
        working_dir: /var/www/html

    db:
        image: mysql:8
        container_name: exchange_rates_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: exchange_rates
        ports:
            - "31306:3306"
